name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Before requesting:** please search [existing issues](https://github.com/YouAM-Network/uam/issues) — someone may have already suggested this.

  - type: textarea
    attributes:
      label: Summary
      description: |
        What would you like to see? Describe the problem you're trying to solve
        or the improvement you'd like.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: |
        How do you think this should work? Code examples, CLI usage, or API
        shape are all helpful. If you're not sure, that's fine too.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Area
      description: Which part of UAM does this relate to?
      multiple: true
      options:
        - CLI (`uam` command)
        - Python SDK
        - TypeScript SDK
        - Relay server
        - Crypto / encryption
        - Contacts / trust
        - Protocol design
        - Documentation
        - Not sure
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or considered alternative approaches?
    validations:
      required: false
